### PR TITLE
Re enable nightlies

### PR DESCRIPTION
**Pull request by jakubgs**
Changes:
* Drops `/stable` page in favor of `/get` for releases
* Drops desktop stuff from nightly and features page
* Drops legacy `/wip` page
* Re-enabled auto-updates of `/nightly` page
* Updates `source/_data/nightlies.yml`

Related: https://github.com/status-im/status-react/pull/9994

### CODE REVIEW

**Comment by Serhy** [comment]
Looks good to me on what's now dev.status.im but I don't know how to get to get "Nightlies" link (and https://dev.status.im/nightlies -> 404) 
And Status Desktop still present on https://dev.status.im/features/?nocdnplease (but leads to /get where no Desktop)

**Comment by jakubgs** [comment]
@Serhy these changes are not present on https://dev.status.im/, you have to build this locally with `yarn build` and look in `public` folder.

Also, it's not https://dev.status.im/nightlies/, it's https://dev.status.im/nightly/, my mistake.

**Comment by Serhy** [comment]
I have 
```$ yarn build
yarn run v1.22.0
$ gulp build
fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5```

Tried google suggestion but no luck yet. 
Anyway, manually removing Desktop div from page source (which is supposed to be) makes me feel that all fine :)

**Comment by jakubgs** [comment]
Weird. Okay, I pushed the changes temporarily from this branch to https://dev.status.im/.

i'll check that error later.

**Comment by jakubgs** [comment]
@jinhojang6 fixed, see if it looks better.

Also, I think we need to do a lot of updates to footer link translations.

**Comment by Serhy** [comment]
https://dev.status.im/ looks ready to rollout. 
But I guess we'll need to update additionally Release links (https://dev.status.im/get) after hotfixed version is ready

**Comment by jakubgs** [comment]
I don't think those links will need an update. The APK might have to be re-uploaded under that name.

**Pull request merged**
