### PR TITLE
docs: fix typo in status_dapp_api.md

### PR DESCRIPTION
**Pull request by zhangyuannie**
before
```js
if(window.ethereum.isStatus {
```
after
```js
if (window.ethereum.isStatus) {
```

### CODE REVIEW

**Comment by zhangyuannie** [comment]
Hey @jakubgs, any chance we could merge this one? Thanks :smiley:

**Review by jakubgs — APPROVED** [review]
Thanks for the fix, I didn't see it because I wasn't pinged originally.

**Comment by jakubgs** [comment]
BTW, commit messages shouldn't be just "commit", because that's useless.

I've modified your commit to have a proper message: https://github.com/status-im/status.im/commit/9751ed48

**Comment by zhangyuannie** [comment]
> BTW, commit messages shouldn't be just "commit", because that's useless.
> 
> I've modified your commit to have a proper message: [9751ed4](https://github.com/status-im/status.im/commit/9751ed48)

Thank you! I thought squash and merge takes the PR's title, but apparently that's not the case for single commit PR. :sweat_smile:

**Pull request merged**
