### PR TITLE
added security repo link

### PR DESCRIPTION
**Pull request by corpetty**
Added a link to the security repo, where all audit information now lives.

### CODE REVIEW

**Comment by corpetty** [comment]
Currently only add English translations

**Comment by corpetty** [comment]
ahh, good call on that, I should have at least done english versions and key changes.

**Comment by jinhojang6** [comment]
English: 
Screen Shot 2019-12-12 at 1 28 35 AM

Korean(I did it):
Screen Shot 2019-12-12 at 12 50 47 AM

Other languages(need to be translated, shows English temporarily):
Screen Shot 2019-12-12 at 12 49 35 AM

**Comment by corpetty** [comment]
lgtm, go ahead and review and push it through

**Comment by corpetty** [comment]
damnit.. my stupid gpg keys aren't setup on this machine, going to merge anyway

**Comment by jinhojang6** [comment]
https://dev.status.im/security/

looks good

**Pull request merged**
