### PR TITLE
Update references_views.md to reflect latest improvements

### PR DESCRIPTION
**Pull request by krisc**

### CODE REVIEW

**Comment by jeluard** [comment]
Did you check arguments are the same for all elements?
Also do you mind doing the same for events and queries?

**Comment by krisc** [comment]
Oh, I actually didn't check that for the already existing components. I will check this real quick

**Comment by krisc** [comment]
Okay, I checked that all the elements are the same for all elements. I will gladly do this for events and queries if @StatusSceptre will put a bounty on them.

**Comment by StatusSceptre** [comment]
@krisc I would love to see some more work done to the existing documentation request for any other bounty considerations.

**Comment by krisc** [comment]
@StatusSceptre maybe I'm misunderstanding you. Do you mean what @jeluard is requesting will be part of this same bounty?

**Comment by StatusSceptre** [comment]
Yes, I’d love to see more documentation input for this bounty! Documentation is usually not part of a bounty, but OSS contributions are recognized. I wanted to help because you asked though.

**Comment by krisc** [comment]
okay, got it!

**Comment by krisc** [comment]
Okay I updated queries and events as well. @jeluard , let me know if the argument formatting for the  `arithmetic` and `ethereum/create-filter` events are okay.

**Comment by jeluard** [comment]
@krisc Looks good to me, thanks! Do you mind squashing your commits?

**Comment by krisc** [comment]
This was my first time trying to squash commits and then I found out I wasn't signing the commits. So I made a brand new pull request so I wouldn't confuse myself. But signing still isn't working... I'll sort this out soon. Sorry for the clutter.

**Comment by krisc** [comment]
Here's the new PR that combines all the changes to one commit https://github.com/status-im/status.im/issues/230

**Pull request closed without merging**
