### PR TITLE
Add a known issues section to the Status-React Quickstart Guide

### PR DESCRIPTION
**Pull request by jinhojang6**
Add a 'known issues' sub section to the Status-React Quickstart Guide
- MacOS 10.15 "Catalina"

### CODE REVIEW

**Comment by jinhojang6** [comment]
To build status-react with MacOS 10.15 "Catalina" or later, we need to go through this nix configuration(https://github.com/status-im/status-react/blob/develop/nix/README.md#known-issues) currently

**Comment by jinhojang6** [comment]
@jakubgs updated the commit. I thought it could have users find the related issue directly not clicking additional links but it looks verbose.

**Comment by jakubgs** [comment]
Unsigned commit my dude.

**Comment by jinhojang6** [comment]
@jakubgs Signed the commit. Thank you for catching it

**Pull request merged**
