### PR TITLE
Swarm - Research/Howto 

### PR DESCRIPTION
**Pull request by sriharikapu**
Please find the documentation on how to set up this website on the swarm.

Here are the URL's for you to access the website: [Status.im](https://swarm.windingtree.com/bzz-raw:/92ddab0307c8ed34578e5911a7aa607ade70b3db9e6719f12c8c77310153b7a8/) 

Useful Links: _https://github.com/sriharikapu/StatusIM-SwarmImplementation.git_

### CODE REVIEW

**Comment by sriharikapu** [comment]
@andytudhope Do you need changes?

**Comment by andytudhope** [comment]
@sriharikapu I was just considering what to do with this. The site you uploaded to swarm doesn't have any of the navigation, and you can't get to the docs or any other part of it really... The tutorial would also need a lot of work, and pointing people to that video is likely more effective right now. Anyway, I really appreciate you doing this, so think that I will payout the bounty for the effort you put in. I need to work with our infrastructure people when they have time to see if we can set this up properly on our own machines...

**Comment by sriharikapu** [comment]
@andytudhope I can upload the entire status.im on the swarm. But my concern is the bounty is too less as it requires me to work more in order to do that. In case if you can create a new issue on gitcoin with a higher bounty I can make sure that every one of your page and navigation is all well aligned and properly redirected. Indeed I thought of doing everything when I am pushing the landing page on swarm but then I can't as It needs more time to do that also the bounty is less. So, I did my best to keep at least the landing page up. 

Indeed am anytime willing to push the status.im complete website with proper navigations and make sure everything is working fine if you are up for it. Am sorry if I hadn't met any of your expectations at sometimes. But I think In all possible ways and try them out to make sure that you get the best solution possible.

It's nice working with you. I wish to work further. cheers!! 🤝

**Comment by andytudhope** [comment]
No no, not all! You're absolutely right that the bounty was just an exploratory one for doing the research, which is why I was more than happy to pay it out. Let me speak a little more with @jakubgs before I put out a full one to move everything over. I share the sentiment re working together - hope to see you around some of those extensions bounties!

**Pull request closed without merging**
