### PR TITLE
Updates references for views, queries, and events to reflect latest improvements.

### PR DESCRIPTION
**Pull request by krisc**

### CODE REVIEW

**Comment by krisc** [comment]
This is for https://github.com/status-im/status.im/issues/230

**Comment by krisc** [comment]
@StatusSceptre just reminding that I still have not received the bounty for this

**Comment by StatusSceptre** [comment]
Thanks @krisc will get this later today!

**Comment by krisc** [comment]
thanks for the kudos :) still waiting on the DAI

**Pull request merged**
