### PR TITLE
PFS draft

### PR DESCRIPTION
**Pull request by cammellos**
Initial draft for PFS, not complete yet

### CODE REVIEW

**Comment by oskarth** [comment]
Would it make sense to merge this as a draft and then improve on it in future PRs? This way it'd be visible on the docs page. Are there some major things that need fixing before this makes sense?

**Comment by cammellos** [comment]
@oskarth makes sense to merge, I can open other PR to update

**Comment by oskarth** [comment]
Eh, seems like it was targeted for the wrong place? @cammellos 

fyi @andytudhope

**Comment by andytudhope** [comment]
Yeah, this wasn't a particularly helpful thing to do good people, but I have fixed it for you. Your doc is now under the `Research` route @cammellos - feel free to make any and all changes there when you are ready 👍 

https://github.com/status-im/status.im/commit/556217b63e77a38e8a7bfe9f2b748deacadd4fec

**Comment by oskarth** [comment]
Thanks @andytudhope, sorry I just looked at the content itself as that was my immediate interest :P

**Pull request merged**
