### PR TITLE
Mailserver + Whisper replacement

### PR DESCRIPTION
**Pull request by hesterbruikman**
Updated to refer to
~~Mailserver~~ > Status node
~~Whisper~~ > Waku

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
That's neat and all, but didn't we agree to call them "history" nodes? Or if needed "Status history nodes"? Pretty sure the mobile application uses the term "history node".

**Comment by jakubgs** [comment]
Yep, it does:
image

**Comment by hesterbruikman** [comment]
You're right, updating there as well: https://github.com/status-im/status-react/pull/11689
Sorry, should have linked the [issue](https://github.com/status-im/status-react/issues/11688) with link to [thread](https://discord.com/channels/624205794384281629/689475399586938931/803844381727522857)

**Comment by jakubgs** [comment]
I see. Well, that's still much better than `mailserver`. I guess I was [vindicated yet again](https://discuss.status.im/t/proposal-rename-mailservers-to-historynodes/1408).

As was @Samyoul [I guess](https://discuss.status.im/t/wherefore-art-thou-mailserver-treatise-on-waku-terminology/1664).

**Comment by hesterbruikman** [comment]
Yeah I like `History node` because it communicates that you connect to get your history. But I get the opportunity that `Status node` is more generic and marketable. And I can imagine at some point history becomes just one of multiple configurations

**Comment by jakubgs** [comment]
@hesterbruikman do we want to roll this out no or wait till the app is updated too?

Also, what about desktop?

**Comment by hesterbruikman** [comment]
I think it's ok to rollout ahead of the mobile PR being merged. There discrepancy as is and I believe the marketing team wants to engage with a thread where our mailserver reference in the FAQ was understandably misinterpreted 

I'll followup with Desktop. Believe they use the same language files as Mobile

**Comment by jakubgs** [comment]
Ah, not for the future please make PRs for the `develop` branch.

**Comment by hesterbruikman** [comment]
> Ah, not for the future please make PRs for the `develop` branch.

Ach, again?! Sorry about that. I was certain it was supposed to be on master instead of develop. But the other way around. Noted!

**Pull request merged**
