### PR TITLE
Create and update a Chinese translation file

### PR DESCRIPTION
**Pull request by jinhojang6**
zh_Hans_CN.yml is added

### CODE REVIEW

**Comment by jinhojang6** [comment]
How can we merge this pull request?

**Comment by jakubgs** [comment]
You need to rebase your branch on `develop`, there are conflicts.

**Comment by jinhojang6** [comment]
Thanks, is it good to go now?

**Comment by jakubgs** [comment]
The e87655cf4951af74c8cd7640712721edebb988b3 is not signed. If you go to the `Commits` tab in this PR you will see it doesn't have a green `Verified` sign.

Make sure you have signing configuration in your `.gitconfig`:
```gitconfig
[user]
    email = your@email
    name = Your Name
    signingkey = YOUR_GPG_KEY_ID
[commit]
    gpgsign = true
[gpg]
    program = gpg2
[alias]
    c  = commit --verbose --no-verify --gpg-sign 
    am = commit --verbose --no-verify --gpg-sign --amend
```
See: https://help.github.com/en/articles/signing-commits

**Comment by jakubgs** [comment]
It's still not signed.
I'd recommend squashing the whole thing into one commit and signing that.

**Comment by jinhojang6** [comment]
I think the commit works well here :

https://github.com/status-im/status.im/pull/368

Let me close this PR if there is no problem on the new commit above

**Pull request closed without merging**
