### PR TITLE
Update CTAs

### PR DESCRIPTION
**Pull request by jinhojang6**
- updated Get Status CTAs based on https://www.figma.com/file/KAdh9HIaJGak5HbRp7SfIa/CTA-improvements?node-id=0%3A1

- minor CSS and copy updates

Test: https://dev-lang.status.im/

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
Looks good, but doesn't this also move the middle top buttons slightly off center?

Not that I care. If you don't think it's easy to fix we can merge.

**Comment by jinhojang6** [comment]
@jakubgs Good point, I updated the nav for wider screens at https://dev-lang.status.im/  (dev-lang branch)

Can you take a look? If it is okay, let me apply the change to this `update-ctas` branch

**Review by jakubgs — APPROVED** [review]
Much better, thanks!

**Comment by jinhojang6** [comment]
@jakubgs Cool, I've updated this branch for PR

**Pull request merged**
