### PR TITLE
[WIP] Update links and styles to prepare for desktop release

### LINKED ISSUE #195: Get status website ready for desktop alpha release
Scope TBD

### PR DESCRIPTION
**Pull request by noman-land**
Fixes #195 

- [x] I added the message about alpha but wasn't sure where to put it. Any ideas?
- [ ] It looks like we don't have a light blue version of the windows logo for the mobile version. Anyone have it?

### On larger screens:
image

### When collapsing on smaller screens:
image

---

### Homepage:
image

cc/ @pablanopete @rachelhamlin @richard-ramos @corpetty @PombeirP @andytudhope @jakubgs @flexsurfer @jeluard @andmironov

### CODE REVIEW

**Comment by pablanopete** [comment]
The message for alpha looks gold where it is in the screenshot imo, did the blue from the logo help issue #2 @noman-land ?

**Comment by noman-land** [comment]
Hey @rachelhamlin, sorry if it wasn't clear, the first screenshot shows what happens on larger screens, the second one shows smaller screens when we have to collapse the buttons when we run out of room. I just wanted to call out both variations so you could see them. It's how the site is currently doing it with just the two buttons. 

As for the build links:

([line 10](https://github.com/status-im/status.im/pull/197/files#diff-71b135cb2157cff62bef48bd4ed24bc1R10)): MacOS: https://ci.status.im/job/status-react/job/combined/job/desktop-macos/4971/artifact/StatusImPackage/StatusIm-181224-165548-797a3a-release.dmg

([line 11](https://github.com/status-im/status.im/pull/197/files#diff-71b135cb2157cff62bef48bd4ed24bc1R11)): Linux: https://ci.status.im/job/status-react/job/combined/job/desktop-linux/4958/artifact/StatusImPackage/StatusIm-181224-165548-797a3a-release.AppImage

([line 12](https://github.com/status-im/status.im/pull/197/files#diff-71b135cb2157cff62bef48bd4ed24bc1R12)): Windows: https://ci.status.im/job/status-react/job/combined/job/desktop-windows/1443/artifact/StatusImPackage/StatusIm-181224-165548-797a3a-release.exe

**Comment by noman-land** [comment]
Also, it would be nice to get a light blue version of the windows logo if we can, you can see it's a little out of blue in the darker blue:

image

**Comment by noman-land** [comment]
Updated alpha message:

### Larger screens:
image

### Smaller screens:
image

**Comment by rachelhamlin** [comment]
Oh no, my bad for misreading. Disclaimer text looks better to me now too. 

@andmironov could you helps us out with a lighter version of the Windows icon?

**Comment by andytudhope** [comment]
Thank you for all the work @noman-land ❤️ Added the commit to refer to right image here: https://github.com/status-im/status.im/commit/e294eadaf63d6747f148eba9759d0ede4e3b66e8

Also, thanks @andmironov - only love for you!

**Pull request merged**
