### PR TITLE
Add Discord logos in the header & footer

### PR DESCRIPTION
**Pull request by jinhojang6**
Local build:

Screen Shot 2019-12-05 at 5 23 09 PM

Screen Shot 2019-12-05 at 5 23 21 PM

links to https://discord.gg/KBk7Uk (Discord community channel)

### CODE REVIEW

**Comment by jakubgs** [comment]
Ops, looks like the invite is invalid:
invalid_invite
I assume it's because it was created from a channel that was removed(`#general`). What we should be using is the server invite, which is: https://discord.gg/YeKgYF

**Comment by jakubgs** [comment]
I fixed it in this commit: b9640a291cd97644e0157f8cdb601edfc1f1aee7
I also moved the URL to the config for easier re-use.

**Comment by jakubgs** [comment]
That looks better:
discord_valid_invite

**Comment by jakubgs** [comment]
Should have noticed this before merging.

**Comment by jinhojang6** [comment]
Good catch and nice work @jakubgs 

The link worked before but there was some change in the server.

BTW, the invite shows your profile as below
KakaoTalk_20191206_091554080

Are you okay with this?

**Comment by jakubgs** [comment]
I think all Discord invites need to have an identity of who created the invite link.

I guess it's fitting since I'm the owner of the server =].

**Pull request merged**
