### PR TITLE
Shared js

### PR DESCRIPTION
**Pull request by samthomson**
Relating to https://github.com/status-im/status.im/issues/168

Added shared-js as sub module, and included common JS from there.

### CODE REVIEW

**Comment by andytudhope** [comment]
Hey @samthomson - is this ready to go (i.e. are you happy with it)?

**Comment by samthomson** [comment]
Actually when testing it I hit issues, but they seem unrelated: https://github.com/status-im/status.im/issues/219

**Comment by samthomson** [comment]
Hi @andytudhope resolved the elastic config issue (thanks to @jakubgs ' suggestion ), have since retested this branch and the menus work as expected :+1:

**Comment by samthomson** [comment]
oh man what happened to this branch? @PombeirP did your force push add all those commits or could I have miss-merged somewhere when rebasing :confused:

**Comment by andytudhope** [comment]
Yeah, he did 😞 Anyway, I force-pushed the state I had locally, hopefully that has fixed things. Just gonna test some stuff quickly and then will look to merge here.

**Comment by PombeirP** [comment]
Sorry for the screw-up @samthomson :-(

**Comment by samthomson** [comment]
I do it all the time @PombeirP  :upside_down_face: c'est la vie :smile:

**Pull request merged**
