### PR TITLE
Generate /get/{platform}/ pages for easier access to downloads

### PR DESCRIPTION
**Pull request by jakubgs**
This makes use of hexo-generator-alias to generate simple HTML redirects.

### CODE REVIEW

**Comment by jakubgs** [comment]
But as @hesterbruikman rightly pointed out this approach does not notify our clicks counting service of these URLs being used:
https://github.com/status-im/status.im/blob/62e65763b878f445c531610e8ff7f0d1af5c4136/themes/navy/layout/layout.ejs#L25-L33
Since it doesn't call any JS, it just redirects using the [`http-equiv="refresh"`](https://www.w3schools.com/tags/att_meta_http_equiv.asp) meta attribute.

**Comment by jakubgs** [comment]
I've verified that adding the the HTML redirect this:
```html
<body><script>navigator.sendBeacon("https://clicks.status.im/clicks/nightly:apk");</script></body>
```
Does correctly trigger a `POST` request to count the click.

**Review by jinhojang6 — APPROVED** [review]

**Comment by jinhojang6** [comment]
Works well on my end. Brilliant

**Comment by hesterbruikman** [comment]
Thanks Jakub!

**Pull request merged**
