### PR TITLE
Typo fixes

### PR DESCRIPTION
**Pull request by timhartmann**
@jakubgs Can you check that and deploy it to a staging branch? After that @j-zerah can check that :)

### CODE REVIEW

**Comment by jakubgs** [comment]
I'll sign the commits myself, but please configure commit signing Tim.

**Comment by jakubgs** [comment]
@j-zerah changes should be available at https://dev.status.im/.

**Comment by j-zerah** [comment]
@jakubgs @timhartmann looks good to me. Thank you

**Comment by jakubgs** [comment]
Cool, pushed to prod.

**Comment by j-zerah** [comment]
thanks @jakubgs muuuuuch better

**Pull request merged**
