### PR TITLE
Adapt documentation to reference Nix

### PR DESCRIPTION
**Pull request by PombeirP**

### CODE REVIEW

**Comment by corpetty** [comment]
When running `make setup` on kubuntu 18.10 it is successful but repeats the installation of nix ad infinitum.  It has to be manually `ctrl-c` and then `make shell` can be performed. 

Worked as intended on Mac OSX 10.14.3

**Comment by corpetty** [comment]
spoke too soon.  On Linux Kubuntu 18.10.  `make shell` failed with the following: 

```
error /home/petty/GitHub/status-im/status-react/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/petty/GitHub/status-im/status-react/node_modules/sha3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@10.9.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v10.9.0/node-v10.9.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.9.0/node-v10.9.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.9.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.9.0/SHASUMS256.txt
gyp info spawn /nix/store/4iv1n45brycl3l4rdln4i4ah0yqlf05i-python-2.7.15/bin/python2
gyp info spawn args [ '/nix/store/lwbdxhjq9a25dw20cspi7vk0snad3r73-nodejs-10.9.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/petty/GitHub/status-im/status-react/node_modules/sha3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/nix/store/lwbdxhjq9a25dw20cspi7vk0snad3r73-nodejs-10.9.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/petty/.node-gyp/10.9.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/petty/.node-gyp/10.9.0',
gyp info spawn args   '-Dnode_gyp_dir=/nix/store/lwbdxhjq9a25dw20cspi7vk0snad3r73-nodejs-10.9.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/petty/.node-gyp/10.9.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/petty/GitHub/status-im/status-react/node_modules/sha3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make[2]: Entering directory '/home/petty/GitHub/status-im/status-react/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
../src/addon.cpp:1:10: fatal error: node.h: No such file or directory
 #include <node.h>
          ^~~~~~~~
compilation terminated.
make[2]: *** [sha3.target.mk:105: Release/obj.target/sha3/src/addon.o] Error 1
make[2]: Leaving directory '/home/petty/GitHub/status-im/status-react/node_modules/sha3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/nix/store/lwbdxhjq9a25dw20cspi7vk0snad3r73-nodejs-10.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Linux 4.18.0-15-generic
gyp ERR! command "/nix/store/lwbdxhjq9a25dw20cspi7vk0snad3r73-nodejs-10.9.0/bin/node" "/nix/store/lwbdxhjq9a25dw20cspi7vk0snad3r73-nodejs-10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/petty/GitHub/status-im/status-react/node_modules/sha3
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0


make[1]: *** [Makefile:117: prepare-android] Error 1
make[1]: Leaving directory '/home/petty/GitHub/status-im/status-react'
Error running dependency install 'make prepare-mobile'

  + done
```

**Comment by PombeirP** [comment]
> spoke too soon. On Linux Kubuntu 18.10. `make shell` failed with the following:

@corpetty I had the same thing yesterday. I believe the problem comes from new child shells not correctly inheriting the Nix environment. Can you please check if you have the following code at the end of `~/.bashrc` (normally you should, that's something I added to the `installers.sh` script)? 

```shell
if [ -e /home/$USER/.nix-profile/etc/profile.d/nix.sh ]; then . /home/$USER/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
```

**Comment by corpetty** [comment]
also, what needs to be done to ready https://status.im/build_status/ with the changes?

**Comment by corpetty** [comment]
> > spoke too soon. On Linux Kubuntu 18.10. `make shell` failed with the following:
> 
> @corpetty I had the same thing yesterday. I believe the problem comes from new child shells not correctly inheriting the Nix environment. Can you please check if you have the following code at the end of `~/.bashrc` (normally you should, that's something I added to the `installers.sh` script)?
> 
> ```shell
> if [ -e /home/$USER/.nix-profile/etc/profile.d/nix.sh ]; then . /home/$USER/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
> ```
> 
> I'm not familiar with the peculiarities of Kubuntu in this area, maybe something different is needed for that distro.

all good

**Comment by PombeirP** [comment]
> all good

Do I need to do anything to the script, or was it just that you got an early version of it which didn't yet handle `.bashrc`?

**Pull request merged**
