### PR TITLE
Update the best practice guide on the security page

### PR DESCRIPTION
**Pull request by jinhojang6**
Update the best practice guide link on https://status.im/security/ 
to https://notes.status.im/Fa9h9kCVRtm82PcgQ31Y7w?view

Had a chat with Tobias about it on the Discord channel

### CODE REVIEW

**Comment by jakubgs** [comment]
Wouldn't it make more sense to just make that a normal page at https://status.im/security-practices?

**Comment by jinhojang6** [comment]
Nice, let me update this PR

**Comment by jinhojang6** [comment]
Added the security best practice at /user_guides/best_security_practices.html

Screen Shot 2020-06-27 at 1 20 57 PM

**Comment by jakubgs** [comment]
I took the liberty to shorten the title and expand a bit the index page.

I'm also wondering if it would make sense to rename the `Developers` section in the header to just `Docs`, like on any other site.
After all if you look at the footer it's called `Documentation`.

What do you think?

**Comment by jinhojang6** [comment]
Thanks @jakubgs . Feel free to edit the title, the index page, and etc. as much as you want.

The word `Developers` in the header was decided by @j-zerah and @rbnpercy. What do you think of using `Docs`?

**Comment by jinhojang6** [comment]
@jakubgs What do you think of merging this PR first and discuss the renaming later? I think the link to the security best practices should be updated.

**Comment by j-zerah** [comment]
@jinhojang6 @jakubgs I was told by our team that "Docs" is not an accurate representation of what lives under the secondary nav as `Contributor Guide` `Specs` and `Tutorials` are not technically docs. 

So can we leave as it. Also, this section will hopefully grow into more of a dev portal.

**Comment by jakubgs** [comment]
@j-zerah I think that's silly. Go to literally ANY project site and the part that has documents like that will be called "Docs".

But whatever.

**Comment by jinhojang6** [comment]
Thanks all

**Pull request merged**
