### PR TITLE
refactor sidebar helper to be recursive

### PR DESCRIPTION
**Pull request by jakubgs**
It took me a while but I've successfully un-fucked the retarded `sidebar` helper function into something that makes sense and is also recursive, which allows us for nesting more sub-entries in the sidebar.

Changes:
* Refactored `siderbar` helper to be recursive, removed lots of useless logic
* Changed the format of the `source/_data/sidebar.yml` file to be a list of objects
* The objects in `source/_data/sidebar.yml` contain `path`, `title`, and optionally `children`
* Moved technical docs from `source/docs` to `source/technical`
* Moved APDU API call docs from `source/keycard_api` to `source/keycard_api/apdu`
* Moved Keycard SDK docs from `source/keycard_api` to `source/keycard_api/sdk`
* Moved everything except `index.html` from `source/security` to `source/security_docs`
  - This was done to allow `/security` to retain its non-sidebar looks
* Removed obsolete references to `Statusphere`

### CODE REVIEW

**Comment by jakubgs** [comment]
This is how the Keycard APDU sidebar changed:
new_apdu_sidebar
Are you fine with this @bitgamma ?

**Comment by bitgamma** [comment]
looks fine to me. Maybe also the SDK part can be made nested?

**Comment by jakubgs** [comment]
Sure, I can do that.

**Comment by jakubgs** [comment]
Fuck it, if no one cares I'll just merge it without reviews because I have the POWAH.

**Pull request merged**
